<?php
// English language variables
//navbar.php
$homePage="Home Page";
$planeTicket="Plane Ticket";
$aboutUs="About Us";
$contactUs="Contact Us";
// index
$indexBannerH1 = "TO WHERE YOU WANT TO BE.";
$indexBannerP = 'You can reach us anytime, anywhere at our call center with the number <a href="tel:4445849" style="text-decoration: none; color: white; font-weight: bolder;">444 5 849</a>.';
$indexOtelRezH2 = "Hotel Reservation";
$indexOtelRezP = "So, the principle you want or we recommend to you, tested hotels with reliability in terms of principle, trust, service quality, and room and meal services in the city you are going to...";
$readMore = "Read more &raquo;";
$visaH2 = "Visa Procedures";
$visaP = "Our company's Visa Department provides service in a consulting style, knowledgeable about every issue, providing service beyond the standard visa application procedures, for the country you want to go to...";
$chinaVisaH2 = "China Visa";
$chinaVisaP = "The required documents for a China visa are as follows: Tourist China visa required documents, Clean record from the Prosecutor's Office, Color copy of ID card, 2 passport-size photos...";
$usaVisaH2 = "USA Visa";
$usaVisaP = "Documents required for a US visa as an employer: Signature Circulars, Activity Certificate with a validity of at least 6 months...";
$servicesH2 = "Our Services";
$servicesH3one = "Airplane Ticket";
$servicesH3two = "Hotel Reservations";
$servicesH3three = "Visa Procedures";
$servicesP3one = 'We have the right to sell <a href="https://www.birucak.com/" title="airplane ticket" rel="noopener noreferrer nofollow" target="_blank">International Airplane Tickets</a> with an IATA certificate. As an Authorized Agency, we provide services without restrictions on transactions related to tickets of all International and National Airlines operating in the Aviation sector.';
$servicesPtwo = 'Do your business relationships force you to travel constantly, circling between countries and cities? Do you need reliable hotels, tested for principle, trust, service quality, room, and meal services in the city you are visiting? We offer hotels from Pensions to 5-star hotels, and moreover, you will stay at <a href="./HTML/otelRez.php">hotels below standard prices.</a>';
$servicesPthree = 'We help you get the visa of the country you want to travel to faster, minimizing your time and financial losses. Our professional consultants provide you with current visa requirements and procedures, focusing on your needs with personalized services. <a href="./HTML/vize.php">Fast visa procedures</a> help you efficiently use financial resources and smoothly carry out your travel plans with up-to-date information.';
$ourCompanyH2 = "Our Company";
$affInstitutionsH2 = "Affiliated Institutions";
$IATAH4 = "IATA";
$IATAP = "The International Air Transport Association (IATA) is a global trade organization that only airlines can become members of. The headquarters of the organization is in Montreal, Canada.";
$TURSABH4 = "TÜRSAB";
$TURSABP = "The Association of Turkish Travel Agencies, short name TÜRSAB, was established with Law No. 1618, which entered into force on September 28, 1972. It is the authorized institution for all transactions of travel agencies.";
$starAllH4 = "STAR ALLIANCE";
$starAllP = "Star Alliance is a global airline alliance headquartered in Frankfurt, Germany. Founded on May 14, 1997, the logo of Star Alliance represents its founding members. Star Alliance has 27 member airlines.";
//Hakkimizda.php
$aboutUsH2 = "About Us";
$aboutUsP = "The aviation sector is the fastest-growing sector in our country in recent years. The transformation of land and sea transportation into air transportation began to gain momentum in 2003 and has shown a continuous growth trend. The civil aviation sector is marked by technological advancements, innovative ideas, the entry of new companies into the sector, and the competitive landscape in terms of services and prices. This indicates that in the near future, air transportation will replace the longstanding land and sea transportation in our country.<br><br>According to statistical data, in the last 10 years, the number of employees in Turkish civil aviation has increased from 65,000 in 2003 to 167,161 by the end of 2012. The revenue, which was 2.2 billion dollars, has also risen to 21.4 billion dollars. This situation is highly satisfactory for our country in terms of employment and revenue growth. In the civil aviation sector, it has been observed that employment at the end of 2012 has increased by 3 times compared to 2003, and revenue has increased 10 times.<br><br>In this relatively new sector, experience is undoubtedly crucial. The founders of our company, who entered the sector in 1999, converted their accumulated experience and gained expertise into investment and service under the umbrella of <a href=\"/sienaTurizm\">Siena Tourism Org. Consulting Ltd. Sti.</a> in 2011. Rather than just 'issuing tickets, providing visa services, and making hotel reservations', with Siena Tourism, we combine all services with our customer-oriented approach providing Help-Service-Reasonable Price-Customer Satisfaction-Openness to Innovations and Developments, ensuring our customers a seamless travel experience and financial savings.<br><br>Our company is the authorized agency, number 7121, of TURSAB and serves as the authorized agency for all domestic flights and some international flights by airlines. Some of our licenses and authorization documents are presented below.";
//iletisim.php
$contactUSAlert ="Your message has been successfully sent.";
$contactUSH2 = "Contact Us";
$contactUsP = '<p>Phone: <a href="tel:4445849" style="text-decoration: none; color: black; font-weight: bolder;">444 5 849</a> / <a href="tel:08508850209" style="text-decoration: none; color: black; font-weight: bolder;">0850 885 0209</a> </p><p>Address:</p><p style="font-size: medium;"> Piri Paşa Mah. Şaban DeresiSk. No:3/A Hasköy Beyoğlu / Istanbul </p><p>Email:</p><p style="font-size: medium;"> <a href="mailto:info@sienaturizm.com">info@sienaturizm.com</a> </p>';
$contactUsForm = '<div class="form-group"><div class="row"><div class="col"> <label for="formGroupExampleInput">Name</label><input type="text" name="isim" id="name" class="form-control" placeholder="Name" required></div><div class="col"> <label for="formGroupExampleInput">Surname</label><input type="text" name="soyad" id="surname" class="form-control" placeholder="Surname"></div></div><br><div class="row"><div class="col"><label for="formGroupExampleInput">E-mail</label><input type="email" name="email" id="email" class="form-control" id="formGroupExampleInput" placeholder="mail" required><br><label for="exampleFormControlTextarea2">Your Message</label><textarea class="form-control" name="Mesaj" rows="5" required></textarea><br><button type="submit" class="btn btn-outline btn-lg g-recaptcha" style="background-color: #19386b; color: white;" data-sitekey="6LdoRS0pAAAAAFddV39p_Yu2SEBQmeAZjlwsZ7K9" data-callback=\'onSubmit\' data-action=\'submit\' id="submit"><b>Send</b></button></div></div></div>';
//otelRez.php
$hotelResH2 = "Hotel Reservation";
$hotelResP = 'Do your business relationships force you to travel constantly, and roam around cities and countries?<br>*So, when you are in a city, do you need reliable hotels that meet your criteria or those recommended by us, with tested principles, trust, service quality, and room and meal services?<br>We offer hotels ranging from guesthouses to 5-star hotels, and even below standard prices, with numerous alternative options in every city-district-region…<br>*Are you a participant or visitor to one of the industry\'s most important fairs? But you are in a foreign city and not familiar with the region. You need a hotel close to the fairground, airport, city center, and even an online invitation for the fair.<br>With us, you are placed in your desired hotel within a maximum of 1 hour... Just focus on your work and adapting to the foreign city, enjoy it.<br><a href="/sienaTurizm">Siena Tourism</a> operates systematically and coordinately with 14,500 hotels worldwide.<br>Note: Our hotel prices are presented to you based on the discounted Hotel Sales List applied to agencies.<br>We provide services for all domestic and international hotels, subject to availability.';
//vize.php
$visaInfoH2 = "Visa Procedures";
$visaInfoP = "Our Visa Department personnel are well-versed in all matters, providing services in a consultant style beyond standard visa procedures, offering the most suitable conditions to prevent you from experiencing time and financial losses in obtaining the visa for the country you want to visit. Travel insurance and flight – <a href='./hotelRes.php'>HOTEL RESERVATIONS</a> are just a few of the complimentary services we provide. Your seamless journey is our limitless gain. To learn the required documents for all countries, you can contact us at <a href='tel:08508851549' style='text-decoration: none; color: black; font-weight: bolder;'>0850 885 1549</a>, <a href='tel:02123691056' style='text-decoration: none; color: black; font-weight: bolder;'>0212 369 1056</a> or email us at <a href='mailto:visa@sienaturizm.com'>visa@sienaturizm.com</a>. Looking forward to working together...";
//cinVize.php
$chinaVisaH2 = "China Visa";
$chinaVisaH3One = "Documents Required for China Visa";
$chinaVisaPOne = "Required documents for Tourist China Visa:<br> Clean criminal record from the prosecutor's office<br> Copy of colored identity card<br> 2 passport-size photos with white background<br> New chipped passport valid for at least 6 months<br> Certificate stating 'No archive record' on clean paper is mandatory.<br> Bank account statement with a minimum of 5000 USD equivalent<br> Please fill out the attached information form and send it to us along with the documents<br>";
$chinaVisaH3Two = "Documents Required for Business China Visa";
$chinaVisaPTwo = "Petition on letterhead (please request a sample petition from our company)<br> Original activity certificate (not older than 6 months)<br> Copy of tax certificate<br> Copy of colored identity card<br> 2 passport-size photos with white background<br> New chipped passport valid for at least 6 months<br> Certificate stating 'No archive record' on clean paper is mandatory.<br> Original invitation from the company in China (if there is no invitation, our company can provide one)<br> Please fill out the attached information form and send it to us along with the documents<br><br>";
$chinaVisaH3Three = "Document List Required from Government Officials";
$chinaVisaPThree = "Valid passport for at least 6 months, not older than 10 years, and your old passports<br> 2 photos with a white background<br> Visa request letter addressed to the consulate<br> Permission letter from the affiliated authority<br> Front and back photocopy of the official institution duty identity card<br> Last 3 months' salary statement<br> Certificate stating 'No archive record' on clean paper is mandatory.<br> Last 3 months' bank statement stamped and signed by the bank or updated account book<br> If available, photocopies of title deeds or vehicle registration certificates<br> Photocopy of ID<br> Flight and <a href='./HTML/hotelRes.php'>hotel reservations</a><br> If available, tour itinerary<br> Overseas travel health insurance<br> Note: Passports older than 10 years are not accepted, and individuals must come in person on the appointment day for Spain applications.<br><br>";
$chinaVisaH3Four = "Document List for Government Officials for Business Visa;";
$chinaVisaPFour = "Valid passport for at least 6 months, not older than 10 years, and your old passports<br> 2 photos with a white background<br> Visa request letter addressed to the consulate<br> Invitation from the company in the destination country with travel dates and<br> names of relevant persons<br> Certificate stating 'No archive record' on clean paper is mandatory.<br> Business Entry Card or participation documents<br> Letter to the consulate<br> Permission letter from the affiliated authority<br> Front and back photocopy of the official institution duty identity card<br> Last 3 months' salary statement<br> Last 3 months' bank statement stamped and signed by the bank or updated account book<br> Photocopy of ID<br> Residence certificate<br> Flight and hotel reservations<br> If available, tour itinerary<br> Overseas travel health insurance<br>";
$chinaVisaH3Five = "Visa Document List for Tradesmen";
$chinaVisaPFive = "Valid passport for at least 6 months, not older than 10 years, and your old passports<br> 2 photos in 3×4 format with a white background<br> Original population registration sample from the civil registration office, original and up-to-date<br> Visa request letter on company letterhead stamped and signed by the authorized person addressed to the consulate<br> Owner's declaration of signature<br> Activity certificate from the relevant professional chamber, dated within the last 3 months<br> Copy of tax certificate, last term<br> Certificate stating 'No archive record' on clean paper is mandatory.<br> If available, copy of the commercial registry newspaper<br> Last 3 months' bank statement stamped and signed by the bank or updated account book<br> Photocopies of title deeds, if available, vehicle registration copies<br> Photocopy of ID, residence certificate<br> Hotel flight reservations, overseas travel health insurance<br><br>";
$chinaVisaH3Six = "Document List for Tradesmen for Business Visa;";
$chinaVisaPSix = "Valid passport for at least 6 months, not older than 10 years, and your old passports<br> 2 photos in 3×4 format with a white background<br> Invitation sent by the company in the country to be visited with travel dates and<br> names of relevant persons<br> Entry card for the fair or participation documents<br> Owner's declaration of signature<br> Certificate stating 'No archive record' on clean paper is mandatory.<br> Activity certificate from the relevant professional chamber, dated within the last 3 months<br> Copy of tax certificate, last term<br> If available, copy of the commercial registry newspaper<br> Last 3 months' bank statement stamped and signed by the bank or updated account book<br> Photocopies of title deeds, if available, vehicle registration copies<br> Photocopy of ID, residence certificate<br> Hotel flight reservations, overseas travel health insurance<br> Original population registration sample from the civil registration office, original and up-to-date<br><br>";
$chinaVisaH3Seven = "VISA DOCUMENT LIST FOR LAWYERS DOCTORS PHARMACISTS";
$chinaVisaPSeven = "Valid passport for at least 6 months, not older than 10 years, and your old passports<br> 2 photos in 3X4 format with a white background<br> Signature statement, if the company is a company<br> Certificate stating 'No archive record' on clean paper is mandatory.<br> Petition addressed to the consulate on letterhead, stamped and signed by the authorized person<br> Activity certificate from the relevant professional chamber, and dated within the last 3 months<br> Lawyers from the Bar Association<br> Doctors from the Medical Chamber<br> Pharmacists from the Pharmacists' Chamber<br> Dentists from the Dentists' Chamber<br> Certificate stating 'No archive record' on clean paper is mandatory.<br> Architects and engineers from the Architects and Engineers' Chamber<br> Photocopy of ID<br> Residence certificate<br> Flight and <a href='./HTML/hotelRes.php'>hotel reservations</a>, if available, tour itinerary<br> If available, overseas travel health insurance<br> Population registration sample with disasters from the civil registry, original and up-to-date<br> Photocopy of ID<br> Residence certificate<br> Hotel flight reservations, if available, tour program<br> If available, overseas travel health insurance<br> Photocopies of title deeds, if available, vehicle registration copies<br>";
$chinaVisaH3Eight = "DOCUMENT LIST FOR LAWYERS DOCTORS PHARMACISTS FOR COMMERCIAL VISA;";
$chinaVisaPEight = "Valid passport for at least 6 months, not older than 10 years, and your old passports<br> 2 photos in 3X4 format with a white background<br> Signature statement, if the company is a company<br> Certificate stating 'No archive record' on clean paper is mandatory.<br> If it is a fair, entry card or participation documents<br> Petition addressed to the consulate on letterhead, stamped and signed by the authorized person, if it is a fair, entry card or participation documents<br> Invitation sent by the company in the country to be visited with travel dates and<br> names of relevant persons<br> Certificate stating 'No archive record' on clean paper is mandatory.<br> Activity certificate from the relevant professional chamber, and dated within the last 3 months<br> Lawyers from the Bar Association<br> Doctors from the Medical Chamber<br> Pharmacists from the Pharmacists' Chamber<br> Dentists from the Dentists' Chamber<br> Certificate stating 'No archive record' on clean paper is mandatory.<br> Architects and engineers from the Architects and Engineers' Chamber<br> Photocopy of ID<br> Residence certificate<br> Flight and hotel reservations, if available, tour itinerary<br> If available, overseas travel health insurance<br> Population registration sample with disasters from the civil registry, original and up-to-date<br> Photocopy of ID<br> Residence certificate<br> Photocopies of title deeds, if available, vehicle registration copies<br>";
//abdVize.php
$usaVisaH2 = "USA Visa";
$usaVisaH3One = "Below is the list of documents required for the USA visa as an employer";
$usaVisaPOne = "Signature Circulars<br>Activity Certificate (must be valid for at least 6 months)<br>Commercial Registry Gazette<br>Tax Certificate (Newly Dated)<br>Letterhead of the Company with a Petition stating the Purpose and Duration of the Stay, stamped and signed<br>Invitation from the Company in the USA for Commercial Travel<br>Company Bank Accounts<br>Personal Bank Accounts<br>Copies of Real Estate Title Deeds<br>Copies of Vehicle Registration Certificates<br>Copies of Marriage Certificates<br>If available, Hotel – Flight Reservations or Tourist Invitation<br>2 Passport Photos with a White Background, 5x5 cm<br>Passport and Previous Passports if any";
$usaVisaH3Two = "List of documents required for visa application for employees on salary";
$usaVisaPTwo = "Signature Circulars of the Company<br>Activity Certificate (must be valid for at least 6 months)<br>Commercial Registry Gazette<br>Tax Certificate (Newly Dated)<br>SSK Entry Declaration<br>Last 3 Months Salary Payslips<br>SSK Service Statement<br>A Petition Stating Travel Details Addressed to the Consulate's Visa Department on the Company's Letterhead, Stamped and Signed<br>Invitation from the Company in the USA for Commercial Travel<br>Company Bank Accounts<br>Personal Bank Accounts for Tourist Travel<br>Copies of Real Estate Title Deeds<br>Copies of Vehicle Registration Certificates<br>Copies of Marriage Certificates<br>If available, Hotel – Flight Reservations or Tourist Invitation<br>Passport and Previous Passports if any<br>2 Passport Photos with a White Background, 5x5 cm";
$usaVisaH3Three = "List of documents required for visa application for housewives";
$usaVisaPThree = "Petition Stating Travel Details, Addressed to the US Consulate Visa Department<br>Copies of Real Estate Title Deeds<br>Copies of Vehicle Registration Certificates<br>Copies of Marriage Certificates<br>If the Spouse is Employed or an Employer, the Documents Listed Above Will Be Attached<br>If Traveling Together, the Valid US Visa Copy of the Spouse<br>Passport (Must be valid for at least 6 months from the date of visa application) and Previous Passports if any<br>If available, Hotel – Flight Reservations or Tourist Invitation<br>2 Passport Photos with a White Background, 5x5 cm";
$usaVisaH3Four = "List of documents required for visa application for retirees";
$usaVisaPFour = "Petition Stating Travel Details, Addressed to the US Consulate Visa Department<br>Retirement ID Copy<br>Bank Statements<br>Copies of Real Estate Title Deeds<br>Copies of Vehicle Registration Certificates<br>Copies of Marriage Certificates<br>Passport (Must be valid for at least 6 months from the date of visa application) and Previous Passports if any<br>If available, Hotel – Flight Reservations or Tourist Invitation<br>2 Passport Photos with a White Background, 5x5 cm";
$usaVisaH3Five = "List of documents required for visa application for students";
$usaVisaPFive = "Petition Stating Travel Details, Addressed to the US Consulate Visa Department<br>Student Certificate (New and in English)<br>If under 18, Consent Letter from Parents<br>If Parents are Employed or Employers, the Documents Listed Above Will Be Attached<br>Parents' Bank Accounts<br>Copies of Real Estate Title Deeds<br>If Traveling Together, Copies of Valid Visas<br>Passport (Must be valid for at least 6 months from the date of visa application) and Previous Passports if any<br>If available, Hotel – Flight Reservations or Tourist Invitation<br>2 Passport Photos with a White Background, 5x5 cm";
$usaVisaH3Six = "List of documents required for visa application for government officials";
$usaVisaPSix = "Petition Stating Travel Details, Addressed to the US Consulate Visa Department<br>Proficiency in English (Exam and Interview Will Be Conducted)<br>Service Certificate and Salary Payslip for the Last 18 Months (Must Be in English)<br>Company Activity Certificate (Must Be in English)<br>Tax Certificate (Newly Dated)<br>SGK Entry Declaration (Must Be in English)<br>Company Bank Accounts<br>Personal Bank Accounts<br>Copies of Real Estate Title Deeds<br>Copies of Vehicle Registration Certificates<br>Copies of Marriage Certificates<br>Passport (Must be valid for at least 6 months from the date of visa application) and Previous Passports if any<br>If available, Hotel – Flight Reservations or Tourist Invitation<br>2 Passport Photos with a White Background, 5x5 cm";
$usaVisaH3Seven = "List of documents required for visa application for tradesmen";
$usaVisaPSeven = "Valid passport for at least 6 months, not older than 10 years and your old passports<br>2 photos 3x4 cm with a white background format behind white 2 photos<br>Population directorate record sample taken from the population directorate, original and up-to-date<br>Visa request letter written to the consulate, signed by the authorized signatory, stamped on the company's letterhead<br>Signature declaration of the company owner<br>Activity certificate from the relevant professional chamber, dated in the last 3 months<br>Tax certificate last period<br>If available, commercial newspaper copy<br>Last 3 months bank account statement, stamped and signed by the bank, or account statement with the current date, which must have a current balance taken within 1 week from the appointment date<br>If available, photocopies of title deeds, vehicle registration copies<br>Photocopy of ID, residence certificate<br>Hotel flight reservations, overseas travel health insurance";
$usaVisaH3Eight = "List of documents required for visa application for lawyers, doctors, pharmacists";
$usaVisaPEight = "Valid passport for at least 6 months, not older than 10 years and your old passports<br>2 photos 3x4 cm with a white background format<br>Signature declaration if it is a company, circulars if it is a company<br>If it is a fair, entry card or documents related to participation in the fair<br>A letter of request addressed to the consulate, stamped and signed by the authorized signatory, written on the letterhead if it is a company, stating that it is related to the consulate if it is a fair<br>Invitation sent by the company in the country to be visited, containing travel dates and names of relevant persons<br>Activity certificate from the relevant professional chamber, dated in the last 3 months<br>For lawyers, from the bar<br>For doctors, from the medical association<br>For pharmacists, from the pharmacists' association<br>For dentists, from the dentists' association<br>For architects and engineers, from the architects and engineers' association<br>Photocopy of ID<br>Residence certificate<br>If there are plane and hotel reservations, tour program<br>Population directorate record sample taken from the population directorate, original and up-to-date, showing parents, spouse, children<br>Last 3 months bank account statement, stamped and signed by the bank, or account statement with the current date, which must have a current balance taken within 1 week from the appointment date<br>If available, photocopies of title deeds, vehicle registration copies";

?>