<?php
//Turkish language variables
//navbar.php
$homePage="Ana Sayfa";
$planeTicket="Uçak Bileti";
$aboutUs="Hakkımızda";
$contactUs="İletişim";
//index
$indexBannerH1 = "OLMAK İSTEDİĞİN YERE.";
$indexBannerP = 'Bize her yerden ve her zaman <a href="tel:4445849"style="text-decoration: none; color: white; font-weight: bolder;">444 5 849</a> nolu çağrı merkezi telefonumuzdan ulaşabilirsiniz.';
$indexOtelRezH2 = "Otel Rezervasyonu";
$indexOtelRezP = "Peki gittiğiniz şehirde İstediğiniz ya da Bizim size önereceğimiz Prensip, güven, hizmet kalitesi, oda ve yemek servisleri test edilmiş, güvenilir Otellere...";
$readMore = "Devamını oku &raquo;";
$visaH2 = "Vize İşlemleri";

$visaP = "Firmamızda Vize Departmanında Görevli, Her konuya vakıf, Standart vize alma Prosedürlerinin dışında Danışman tarzında hizmet vererek, Gitmek istediğiniz...";
$chinaVisaH2 = "Çin Vizesi";
$chinaVisaP = "Çin vizesi için gerekli belgeler Aşşağıdaki Gibidir Turistik Çin vizesi gerekli evraklar Savcılıktan temiz kagıdı Renkli nüfus cüzdan fotokopisi 2 tane arka...";
$usaVisaH2 = "Amerika Vizesi";
$usaVisaP = "İş veren olarak amerika vizesi için hazırlanması gereken evrak listesi Aşşağıdaki Gibidir İmza Sirküleri
Faaliyet Belgesi En az 6 ay geçerliliği olması...";
$servicesH2 = "Hizmetlerimiz";
$servicesH3one = "Uçak Bileti";
$servicesH3two = "Otel Rezervasyonları";
$servicesH3three = "Vize İşlemleri";
$servicesP3one = '<a href="https://www.birucak.com/" title="uçak bileti" rel="noopener noreferrer nofollow" target="_blank">Uluslararası Uçak Bileti satışı</a> yapabilme hakkı sunan IATA belgesine sahibiz. Alt Acente değil, Yetkili Acente olarak hizmet sunmakta; Havacılık sektöründe faaliyet gösteren Tüm Uluslararası ve Ulusal Havayolu firmalarının biletleri ile ilgili işlemleri kısıtlama olmaksızın yapabilmekteyiz.';
$servicesPtwo = 'Ticari ilişkileriniz sizleri devamlı seyahat etmeye, ülke-şehir dolaşmaya mı mecbur bırakıyor? Peki gittiğiniz şehirde İstediğiniz ya da Bizim size önereceğimiz Prensip, güven, hizmet kalitesi, oda ve yemek servisleri test edilmiş, güvenilir Otellere mi ihtiyacınız var? Pansiyon’dan 5 Yıldızlı Otellere üstelik <a href="./HTML/otelRez.php">standart fiyatların daha altında konaklayacağınız oteller sunarız.</a>';
$servicesPthree = 'Seyahat etmek istediğiniz ülkenin vizesini daha hızlı almanızı sağlayarak zaman ve mali kayıplarınızı minimumda tutarız. Profesyonel danışmanlarımız, güncel vize gereksinimlerini ve prosedürlerini size sunar ve kişiselleştirilmiş hizmetlerle ihtiyaçlarınıza odaklanır. <a href="./HTML/vize.php">Hızlı vize işlemleri</a>, mali kaynakların verimli kullanımı ve güncel bilgilerle seyahat planlarınızı sorunsuzca gerçekleştirmenize yardımcı oluruz.';
$ourCompanyH2 = "Şirketimiz";
$affInstitutionsH2 = "Bağlı Bulunduğumuz Kurumlar";
$IATAH4 = "IATA";
$IATAP = "Uluslararası Hava Taşımacılığı Birliği(IATA), sadece havayolu şirketlerinin üye olabildiği, uluslararası bir ticaret kuruluşudur. Kurumun merkezi Kanada'nın Montreal şehrindedir.";
$TURSABH4 = "TÜRSAB";
$TURSABP = "Türkiye Seyahat Acenteları Birliği, kısa adıyla TÜRSAB, 28 Eylül 1972 tarihinde yürürlüğe giren 1618 sayılı kanun ile kurulmuş, seyahat acentelarının kuruluş işlemlerinden itibaren tüm işlemlerinde yetkili kurumdur.";
$starAllH4 = "STAR ALLİANCE";
$starAllP = "Star Alliance Almanya'nın Frankfurt şehri merkezli küresel havayolu ittifakı. 14 Mayıs 1997'de kurulan Star Alliance'ın logosu, kurucu üyeleri temsil etmektedir. 27 üyesi bulunan Star Alliance'a bağlı havayolu.";
//Hakkimizda.php
$aboutUsH2 = "Hakkımızda";
$aboutUsP = "Havacılık sektörü, ülkemizde son yılların en hızlı büyüyen sektörüdür. Kara ve deniz yolu ulaşımlarının havayolu ulaşımına dönüşmeye başlaması 2003 yılında ivme kazanmış ve giderek büyüme eğilimi göstermektedir. Sivil havacılık sektörü, teknolojik gelişmeler, yenilikçi fikirler, sektöre giriş yapan yeni şirketler ve bu şirketlerin hizmet ve fiyat alanındaki rekabetleri göstermektedir ki, ülkemizde öteden beri var olan kara ve deniz yolu taşımacılığının yerini yakın gelecekte havayolu taşımacılığı alacaktır.<br><br>İstatistiki verilere göre son 10 yılda Türk sivil havacılığının 2003 yılında 65 bin olan çalışan sayısının 2012 sonu itibarıyla 167 bin 161 kişiye, 2,2 milyar dolar olan cirosunun da 21,4 milyar dolara yükselmiştir. Bu durum, ülkemiz açısından istihdam ve ciro artış rakamlarının son derece memnun edici hal alması demektir. Sivil havacılık sektöründe istihdamın 2012 yıl sonu itibarıyla 2003 yılına göre 3, cironun ise 10 katına çıktığı gözlenilmiştir.<br><br>Oldukça yeni sayılacak bu sektörde şüphesiz ki tecrübe ve deneyim son derece önemlidir. Havacılık sektörünün gelişmeye başladığı yıllardan daha önce; 1999 yılında sektöre dahil olan firma kurucularımız, biriktirdikleri tecrübe ve kazandıkları deneyimleri 2011 yılında <a href=\"/sienaTurizm\">Siena Turizm Org.Dan.Tic.Ltd.Şti.</a> çatısı altında yatırım ve hizmete dönüştürmüşler, işi sadece 'Bilet kesimi,<a href=\"./HTML/vize.php\">Vize Hizmetleri</a>,<a href=\"./HTML/otelRez.php\">Otel rezervasyonları</a> yapmak'dan ziyade Siena Turizm ile, tüm hizmetler için satış öncesi ve sonrası sağladığımız Yardım-Hizmet-Uygun Fiyat-Müşteri Memnuniyeti-Yenilikler ve Gelişmelere açık olan hizmet anlayışımızla birleştirerek müşterilerimize sorunsuz seyahat ve maddi tasarruf sağlamaktayız.<br><br>Şirketimiz TURSAB'ın 7121 Numaralı acentası olup, tüm iç hat ve bazı dış hat seferleri yapan havayolu firmalarının yetkili acentası görevini yürütmektedir. Sahip olduğumuz lisans ve yetki belgelerinden bazıları aşağıda istifadenize sunulmuştur.";
//iletisim.php
$contactUSAlert ="Mesajınız Başarılı şekilde İletilmiştir.";
$contactUSH2 = "Bize Ulaşın";
$contactUsP = '<p>Telefon: <a href="tel:4445849" style="text-decoration: none; color: black; font-weight: bolder;">444 5 849</a> / <a href="tel:08508850209" style="text-decoration: none; color: black; font-weight: bolder;">0850 885 0209</a> </p><p>Adres:</p><p style="font-size: medium;"> Piri Paşa Mah. Şaban DeresiSk. No:3/A Hasköy Beyoğlu / İstanbul </p><p>Email:</p><p style="font-size: medium;"> <a href="mailto:info@sienaturizm.com">info@sienaturizm.com</a> </p>';
$contactUsForm = '<div class="form-group"><div class="row"><div class="col"> <label for="formGroupExampleInput">İsim</label><input type="text" name="isim" id="name"class="form-control" placeholder="İsim" required></div><div class="col"> <label for="formGroupExampleInput">Soyad</label><input type="text" name="soyad" id="surname" class="form-control" placeholder="Soyad"></div></div><br><div class="row"><div class="col"><label for="formGroupExampleInput">E-mail</label><input type="email" name="email" id="email" class="form-control" id="formGroupExampleInput" placeholder="Mail" required><br><label for="exampleFormControlTextarea2">Mesajınız</label><textarea class="form-control" name="Mesaj" rows="5" required></textarea><br><button class="btn btn-outline btn-lg g-recaptcha" style="background-color: #19386b; color: white;" data-sitekey="6LdoRS0pAAAAAFddV39p_Yu2SEBQmeAZjlwsZ7K9" data-callback=\'onSubmit\' data-action=\'submit\' id="demo-form">Gönder</button></div></div></div>';
//otelRez.php
$hotelResH2 = "Otel Rezervasyonu";
$hotelResP = 'Ticari ilişkileriniz sizleri devamlı seyahat etmeye, ülke-şehir dolaşmaya mı mecbur bırakıyor?<br>*Peki gittiğiniz şehirde İstediğiniz ya da Bizim size önereceğimiz Prensip, güven, hizmet kalitesi, oda ve yemek servisleri test edilmiş, güvenilir Otellere mi ihtiyacınız var?<br>Pansiyon’dan 5 Yıldızlı Otellere üstelik standart fiyatların daha altında konaklayacağınız oteller sunarız.<br>Üstelik her şehir-ilçe-bölgede çok fazla alternatif seçenekleriyle…<br>*Sektörün en önemli Fuarlarından birine katılımcı ya da ziyaretçisiniz. Fakat yabancı bir şehirdesiniz ve bölgeye hakim değil siniz. Fuar alanına, Havalimanına, Şehir merkezine yakın bir otele ve hatta Fuar için online Davetiye ye ihtiyacınız var.<br>Bizimle birlikte maksimum 1 saat içinde istediğiniz otele yerleştirildiniz bile… Siz İşe ve yabancı şehre adapte olmaya bakın, keyfini çıkarın.<br><a href="/sienaTurizm">Siena Turizm</a> Tüm Dünya’da 14.500 Otel ile sistemli, koordineli şekilde çalışmaktadır.<br>Not: Otel Fiyatlarımız Acentelere uygulanan indirimli Otel Satış Listesi baz alınarak tarafınıza sunulmaktadır.<br>Yurt içi ve Yurt Dışı tüm oteller için, müsaitlik durumunda hizmet vermekteyiz.';
//vize.php
$visaInfoH2 = "Vize İşlemleri";
$visaInfoP = "Firmamızda Vize Departmanında Görevli, Her konuya vakıf, Standart vize alma Prosedürlerinin dışında Danışman tarzında hizmet vererek, Gitmek istediğiniz Ülkenin vizesini ne şekilde daha hızlı alabilirsiniz sorusunun cevaplarını bilen Personelimizle zaman ve mali kayıplara uğramanızı engellemek için en uygun koşulları sunarız. Vize almak için gerekli olan SEYAHAT SİORTASI ve UÇAK – <a href='./otelRez.php'>OTEL REZERVASYONLARI</a> da tarafımızdan Ücretsiz sunulan hizmetlerden sadece birkaçıdır. Sizlerin sorunsuz seyahati bizim sınırsız kazancımız olacaktır. Tüm Ülkeler için gerekli olan belgeleri öğrenmek için <a href='tel:08508851549' style='text-decoration: none; color: black; font-weight: bolder;'>0850 885 1549</a>, <a href='tel:02123691056' style='text-decoration: none; color: black; font-weight: bolder;'>0212 369 1056</a> numaralı telefonlardan veya <a href='mailto:vize@sienaturizm.com'>vize@sienaturizm.com</a> mail adresimizden bizlere ulaşabilirsiniz. Birlikte çalışabilmek dileğiyle...";
//cinVize.php
$chinaVisaH2 = "Çin Vizesi";
$chinaVisaH3One = "Çin vizesi için gerekli belgeler Aşşağıdaki Gibidir";
$chinaVisaPOne = "Turistik Çin vizesi gerekli evraklar:<br> Savcılıktan temiz kagıdı<br> Renkli nüfus cüzdan fotokopisi<br> 2 tane arka fon beyaz vesikalık resim<br> En az 6 ay geçerli yeni çipli pasaport<br> Temiz kağıdında arşiv kaydı yoktur yazısı bulunması zorunludur.<br> En az 5000 usd karşılıgı banka hesap cüzdanı<br> Ekli dosyadaki bilgi formunuda doldurup evraklar ile birlikte bize ulaştırın lütfen<br>";
$chinaVisaH3Two = "Ticari Çin vizesi gerekli evraklar";
$chinaVisaPTwo = "Antetli kağıda dilekçe(dilekçe örneğini firmamızdan isteyin lütfen)<br> Orijinal faaliyet belgesi(6 aydan eski olmayacak)<br> Vergi levhası fotokopisi<br> Renkli nüfus cüzdan fotokopisi<br> 2 tane arka fon beyaz vesikalık resim<br> En az 6 ay geçerli yeni çipli pasaport<br> Temiz kağıdında arşiv kaydı yoktur yazısı bulunması zorunludur.<br> Çindeki firmadan orijinal davetiye ( davetiye yoksa şirketimiz davetiye temin etmektedir)<br> Ekli dosyadaki bilgi formunu da doldurup evraklar ile birlikte bize ulaştırın lütfen<br><br>";
$chinaVisaH3Three = "Devlet Memurların’dan İstenen Evrak Listesi";
$chinaVisaPThree = "En az 6 ay geçerli pasaport son 10 yıldan eski olmamalı ve eski pasaportlarınız<br> Arka fonu beyaz 2 adet fotoğraf<br> Konsolosluga hitaben yazılmış vize talep dilekçesi<br> Bağlı olduğu makamdan izin belgesi<br> Resmi kurum görev kimlik kartının önlü arkalı fotokopisi<br> Son 3 aylık maaş bordrosu<br> Temiz kağıdında arşiv kaydı yoktur yazısı bulunması zorunludur.<br> Son 3 aylık banka hesap dökümü bankadan kaşeli imzalı veya hesap cüzdanı güncel tarihli<br> hesap bakiyesi bulunan ve randevu gününden Son 1 hafta içinde alınmış olması gerekir<br> Tapu fotokopileri varsa araç ruhsat fotokopileri varsa<br> Kimlik fotokopisi<br> Uçak ve <a href='./HTML/otelRez.php'>otel rezervasyonları</a><br> Varsa tur programı<br> Yurt dışı seyahat sağlık sigortası<br> Dikkat: 10 seneden eski pasaport kabul edilmez ve İspanya başvurusunda kişiler randevu günü<br> şahsen gelmelidirler.<br><br>";
$chinaVisaH3Four = "Devlet memurları’na Ticari Vize İçin Gerekli Evrak Listesi;";
$chinaVisaPFour = "En az 6 ay geçerli pasaport son 10 yıldan eski olmamalı ve eski pasaportlarınız<br> Arka fonu beyaz 2 adet fotoğraf<br> Konsolosluğuna hitaben yazılmış vize talep dilekçesi<br> Davetiye gideceğiniz ülkede ki şirket tarafından yollanmış üzerinde seyahat tarihlerine ve<br> ilgili kişilerin isimleri yazdığı davetiye<br> Temiz kağıdında arşiv kaydı yoktur yazısı bulunması zorunludur.<br> Faaliyet İzin Kartı veya katılım belgeleri<br> Konsolosluğa hitaben dilekçe<br> Bağlı olduğu makamdan izin belgesi<br> Resmi kurum görev kimlik kartının önlü arkalı fotokopisi<br> Son 3 aylık maaş bordrosu<br> Son 3 aylık banka hesap dökümü bankadan kaşeli imzalı veya hesap cüzdanı güncel tarihli<br> hesap bakiyesi bulunan ve randevu gününden son 1 hafta içinde alınmış olması gerekir<br> Kimlik fotokopisi<br> İkametgah belgesi<br> Uçak ve otel rezervasyonları<br> Varsa tur programı<br> Yurt dışı seyahat sağlık sigortası<br>";
$chinaVisaH3Five = "Esnaflar İçin Vize Evrak Listesi";
$chinaVisaPFive = "En az 6 ay geçerli pasaport son 10 yıldan eski olmamalı ve eski pasaportlarınız<br> 3×4 formatında arka fonu beyaz 2 adet fotoğraf<br> Vukatlı nüfus kayıt örneği, nüfus müdürlüğünden alınmış aslı ve yeni tarihli<br> Şirket antetli kağıdına kaşeli ve imza yetkilisi tarafından imzalanmış baskonsolosluğa yazılmış vize talep dilekçesi<br> Firma sahibinin imza beyannamesi<br> Faaliyet belgesi, bağlı bulunduğu meslek odasından son 3 ay tarihli<br> Vergi levhası fotokopisi, son dönem<br> Temiz kağıdında arşiv kaydı yoktur yazısı bulunması zorunludur.<br> Ticari sicil gazetesi fotokopisi varsa<br> Son 3 aylık banka hesap dökümü bankadan kaşeli imzalı veya hesap cüzdanı güncel tarihli<br> hesap bakiyesi bulunan randevu gününden son 1 hafta içinde alınmış olması gerekir<br> Tapu fotokopileri varsa araç ruhsat fotokopiler<br> Kimlik fotokopisi, ikametgah belgesi<br> Otel uçak rezervasyonları, yurt dışı seyahat sağlık sigortası<br><br>";
$chinaVisaH3Six = "Esnaflar İçin Ticari Vize Evrak Listesi;";
$chinaVisaPSix = "En az 6 ay geçerli pasaport son 10 yıldan eski olmamalı ve eski pasaportlarınız<br> 3×4 formatında arka fonu beyaz 2 adet fotoğraf<br> Davetiye gidilecek ülkedeki şirket tarafından yollanmış üzerinde seyahat tarihlerine ve<br> ilgili kişilerin isimleri yazdığı davetiye<br> Fuar işe giriş kartı veya katılım belgeleri<br> Firma sahibinin imza beyannamesi<br> Temiz kağıdında arşiv kaydı yoktur yazısı bulunması zorunludur.<br> Faaliyet belgesi, bağlı bulunduğu meslek odasından son 3 ay tarihli<br> Vergi levhası fotokopisi, son dönem<br> Ticari sicil gazetesi fotokopisi varsa<br> Son 3 aylık banka hesap dökümü bankadan kaşeli imzalı veya hesap cüzdanı güncel tarihli<br> hesap bakiyesi bulunan randevu gününden son 1 hafta içinde alınmış olması gerekir<br> Tapu fotokopileri varsa araç ruhsat fotokopiler<br> Kimlik fotokopisi, ikametgah belgesi<br> Otel uçak rezervasyonları, yurt dışı seyahat sağlık sigortası<br> Vukatlı nüfus kayıt örneği, nüfus müdürlüğünden alınmış aslı ve yeni tarihli<br><br>";
$chinaVisaH3Seven = "AVUKAT DOKTOR ECZACILAR İÇİN VİZE EVRAK LİSTESİ";
$chinaVisaPSeven = "En az 6 ay geçerli pasaport son 10 yıldan eski olmamalı ve eski pasaportlarınız<br> 3X4 Formatında arka fonu beyaz 2 adet fotoğraf<br> İmza beyannamesi, şirket ise şirketin sirküleri<br> Temiz kağıdında arşiv kaydı yoktur yazısı bulunması zorunludur.<br> Antetli kağıdına kaşeli ve imza yetkilisi tarafından imzalanmış baskonsolosluğuna hitaben<br> yazılmış dilekçe<br> Faaliyet belgesi, bağlı olduğu meslek odasından ve son 3 ay tarihli<br> Avukatlar barodan<br> Doktorlar tabibler odasından<br> Eczacılar eczacılar odasından<br> Diş hekimleri diş hekimleri odasından<br> Mimarlar ve mühendisler mimarlar ve mühendisler odasından<br> Vergi levhası fotokopisi, son dönem<br> Ticaret sicil fotokopileri, şirket ise<br> Son 3 aylık banka hesap dökümü bankadan kaşeli imzalı veya hesap cüzdanı güncel tarihli<br> hesap bakiyesi bulunan randevu gününden son 1 hafta içinde alınmış olması gerekmektedir<br> Tapu fotokopileri varsa araç ruhsat fotokopileri<br> Vukuatlı nüfus kayıt örneği, nüfus müdürlüğünden alınmış aslı ve yeni tarihli, anne baba eş<br> çocukları gösteren<br> Kimlik fotokopisi<br> İkametgah belgesi, uçak ve otel rezervasyonları, varsa tur programı<br><br>";
$chinaVisaH3Eight = "AVUKAT DOKTOR ECZACILAR İÇİN TİCARİ VİZE EVRAK LİSTESİ;";
$chinaVisaPEight = "En az 6 ay geçerli pasaport son 10 yıldan eski olmamalı ve eski pasaportlarınız<br> 3X4 Formatında arka fonu beyaz 2 adet fotoğraf<br> İmza beyannamesi, şirket ise şirketin sirküleri<br> Temiz kağıdında arşiv kaydı yoktur yazısı bulunması zorunludur.<br> Fuar ise giriş kartı veya katılım belgeleri<br> Antetli kağıdına kaşeli ve imza yetkilisi tarafından imzalanmış baskonsolosluğuna hitaben<br> yazılmış dilekçe, fuar ise giriş kartı veya katılım belgeleri<br> Davetiye, gidilecek ülkedeki şirket tarafından yollanmış üzerinde seyahat tarihlerine ve<br> ilgili kişilerin isimleri yazdığı davetiye<br> Faaliyet belgesi, bağlı olduğu meslek odasından ve son 3 ay tarihli<br> Avukatlar barodan<br> Doktorlar tabibler odasından<br> Eczacılar eczacılar odasından<br> Diş hekimleri diş hekimleri odasından<br> Temiz kağıdında arşiv kaydı yoktur yazısı bulunması zorunludur.<br> Mimarlar ve mühendisler mimarlar ve mühendisler odasından<br> Kimlik fotokopisi<br> İkametgah belgesi<br> Uçak ve otel rezervasyonları, varsa tur programı<br> Yurt dışı seyahat sağlık sigortası<br> Vukuatlı nüfus kayıt örneği, nüfus müdürlüğünden alınmış aslı ve yeni tarihli, anne baba eş<br> çocukları gösteren<br> Son 3 aylık banka hesap dökümü bankadan kaşeli imzalı veya hesap cüzdanı güncel tarihli<br> hesap bakiyesi bulunan randevu gününden son 1 hafta içinde alınmış olması gerekmektedir<br> Tapu fotokopileri varsa araç ruhsat fotokopileri<br>";
//abdVize.php
$usaVisaH2 = "Amerika Vizesi";
$usaVisaH3One = "İş veren olarak Amerika vizesi için hazırlanması gereken evrak listesi Aşağıdaki Gibidir";
$usaVisaPOne = "İmza Sirküleri<br>Faaliyet Belgesi ( En az 6 ay geçerliliği olması gerekmektedir.)<br>Ticari Sicil Gazetesi<br>Vergi Levhası ( Yeni Tarihli)<br>Şirketin Antetli Kağıdına Gidiş Amacını ve Kalış Süresini kapsayacak Dilekçe Kaşeli ve imzalı<br>Ticari Seyahatler İçin Amerika’daki Firmadan Davetiye<br>Şirketin Banka Hesapları<br>Şahsi Banka Hesapları<br>Gayrimenkul Tapu Fotokopileri<br>Araç Ruhsat Fotokopileri<br>Evlilik Cüzdan Fotokopisi<br>Varsa Otel – Uçak Rezervasyonları veya Turistik Davetiye<br>2 Adet Arka Fon Beyaz 5×5 Biyometrik Fotoğraf<br>Pasaport ve Varsa Eski Pasaportlar";
$usaVisaH3Two = "Bordrolu Çalışanlar için hazırlanması gereken vize başvuru evrak listesi";
$usaVisaPTwo = "Çalıştığı Şirketin İmza Sirküleri<br>Faaliyet Belgesi ( En az 6 ay geçerliliği olması gerekmektedir.)<br>Ticari Sicil Gazetesi<br>Vergi Levhası ( Yeni Tarihli )<br>SSK İşe Giriş Bildirgesi<br>Son 3 Aylık Maaş Bordrosu<br>SSK Hizmet Dökümü<br>Şirketin Antetli Kağıdına Konsolosluğun Vize Departmanına Hitaben Yazılmış Seyahat Detaylarını Belirten Dilekçe Kaşeli-İmzalı<br>Ticari Seyahatler İçin Amerika’da Gidilecek Olan Firmadan Davetiye<br>Şirketin Banka Hesapları<br>Turistik Seyahatler İçin Şahsi Banka Hesapları<br>Gayrimenkul Tapu Fotokopileri<br>Araç ruhsat Fotokopisi<br>Evlilik Cüzdanı Fotokopisi<br>Varsa Otel –Uçak Rezervasyonları veya Turistik Davetiye<br>Pasaport ve Varsa Eski Pasaportlar<br>2 Adet 5×5 Arka Fon Beyaz Biyometrik Fotoğraf";
$usaVisaH3Three = "Ev hanımları için hazırlanması gereken vize başvuru evrak listesi";
$usaVisaPThree = "Amerika Konsolosluğu Vize Departmanına Hitaben Yazılmış ,Seyahat Detaylarını Belirten Dilekçe<br>Gayrimenkul Tapu Fotokopileri<br>Araç Ruhsat fotokopisi<br>Evlilik Cüzdan Fotokopisi<br>Eşi Çalışıyor veya İşveren ise Yukarıda Belirtilen Evraklar Eklenecektir.<br>Birlikte Seyahat Edilecek İse Eşinin Geçerli Amerika Vize Fotokopisi<br>Pasaport ( Vize Başvurusu itibari ile en az 6 ay geçerliliği olması gerekmektedir.) ve Varsa Eski Pasaportlar<br>Varsa Otel – Uçak Rezervasyonları veya Turistik Davetiye<br>2 Adet Arka Fon Beyaz 5×5 Biyometrik Fotoğraf";
$usaVisaH3Four = "Emekliler için hazırlanması gereken vize başvuru evrak listesi";
$usaVisaPFour = "Amerika Konsolosluğu vize Departmanına Hitaben Yazılmış ,Seyahat Detaylarını Belirten Dilekçe<br>Emekli Cüzdan Fotokopisi<br>Banka Hesapları<br>Gayrimenkul Tapu Fotokopileri<br>Araç Ruhsat Fotokopisi<br>Evlilik Cüzdan Fotokopisi<br>Pasaport ( Vize Başvuru Tarihi itibari ile en az 6 ay geçerliliği olması gerekmektedir.) Ve Varsa Eski Pasaportlar<br>Varsa Otel – Uçak Rezervasyonları veya Turistik Davetiye<br>2 Adet Arka Fon Beyaz 5×5 Biyometrik Fotoğraf";
$usaVisaH3Five = "Öğrenci için hazırlanması gereken vize başvuru evrak listesi";
$usaVisaPFive = "Amerika Konsolosluğu Vize Departmanına Hitaben Yazılmış ,Seyahat Detaylarını Belirten Dilekçe<br>Öğrenci Belgesi ( Yeni Tarihli ve İngilizce)<br>18 Yaşını Doldurmamış ise Anne ve Babadan Muvafakatname<br>Anne-Baba Çalışıyor veya İş Veren İse Yukarıdaki Evraklar Eklenecektir.<br>Anne-Babanın Banka Hesapları<br>Gayrimenkul Tapu Fotokopileri<br>Birlikte Seyahat Edilecek ise Geçerli Vizelerinin fotokopileri<br>Pasaport ( Vize Başvuru Tarihi itibari ile en az 6 ay geçerliliği olması gerekmektedir.) Ve Varsa Eski Pasaportlar<br>Varsa Otel – Uçak Rezervasyonları veya Turistik Davetiye<br>2 Adet Arka Fon Beyaz 5×5 Biyometrik Fotoğraf";
$usaVisaH3Six = "Devlet memurları için hazırlanması gereken vize başvuru evrak listesi";
$usaVisaPSix = "Amerika Konsolosluğu Vize Departmanına Hitaben Yazılmış ,Seyahat Detaylarını Belirten Dilekçe<br>En Az Orta Derecede İngilizce Bilen (Sınav ve Mülakat Yapılacaktır.)<br>18 Ay boyunca çalıştığınıza Dair Hizmet Belgesi ve Maaş Bordrosu ( İngilizce Olmalıdır.)<br>Şirketin Faaliyet Belgesi ( İngilizce Olmalıdır.)<br>Vergi Levhası ( Yeni Tarihli )<br>SGK İşe Giriş Bildirgesi ( İngilizce Olmalıdır.)<br>Şirketin Banka Hesapları<br>Şahsi Banka Hesapları<br>Gayrimenkul Tapu Fotokopileri<br>Araç Ruhsat Fotokopileri<br>Evlilik Cüzdan Fotokopisi<br>Pasaport ( Vize Başvuru Tarihi itibari ile en az 6 ay geçerliliği olması gerekmektedir.) Ve Varsa Eski Pasaportlar<br>Varsa Otel – Uçak Rezervasyonları veya Turistik Davetiye<br>2 Adet Arka Fon Beyaz 5×5 Biyometrik Fotoğraf";
$usaVisaH3Seven = "Esnaflar için hazırlanması gereken vize başvuru evrak listesi";
$usaVisaPSeven = "En az 6 ay gecerli pasaport son 10 yıldan eski olmamalı ve eski pasaportlarınız<br>3×4 formatında arka formatı beyaz 2 adet fotograf<br>Vukuatlı nufus kayıt örneği nufus müdürlüğünden alınmış aslı ve yeni tarihli<br>Şirket antetli kagıdına kaşeli ve imza yetkilisi tarafından imzalanmış baskonsolosluga yazılmıs vize talep dilekcesi<br>Firma sahibinin imza beyannamesi<br>Faaliyet belgesi baglı bulundugu meslek odasından son 3 ay tarihli<br>Vergi levhası fotokoposi son dönem<br>Ticari sicil gazetesi fotokopisi var ise<br>Son 3 aylık banka hesap dökümü bankadan kaşeli imzalı veya hesap cüzdanı güncel tarihli hesap bakiyesi bulunan randevu gününden son 1 hafta içinde alınmıs olması gerekir<br>Tapu fotokopileri varsa arac ruhsat fotokopiler<br>Kimlik fotokopisi ikametgah belgesi<br>Otel ucak rezervasyonları yurt dışı seyahat saglık sigortası";
$usaVisaH3Eight = "Avukat, Doktor, Eczacılar için hazırlanması gereken vize başvuru evrak listesi";
$usaVisaPEight = "En az 6 ay gecerli pasaport son 10 yıldan eski olmamalı ve eski pasaportlarınız<br>3X4 Formatında arka formatı beyaz 2 adet fotograf<br>İmza beyannamesi şirket ise sirküleri<br>Fuar ise giriş kartı veya katılmaya ilişkin belgeler<br>Antetli kagıdına kaşeli ve imza yetkilisi tarafından imzalanmış baskonsolosluguna hitaben yazilmış dılekce fuar ise giriş kartı veya katılmaya ilişkin belgeler<br>DavetiyeGidilecek ülkedeki şirketten tarafından yollanmış üzerinde seyahat tarihlerine ve ilgili kişilerin isimleri yazdıgı davetiye<br>Faaliyet belgesi baglı oldugu meslek odasından ve son 3 ay tarıhlı<br>Avukatlar barodan<br>Doktorlar tabibler odasından<br>Eczacılar eczacılar odasından<br>Diş hekimleri diş hekimleri odasından<br>Mimarlar ve mühendisler mimarlar ve mühendisler odasından<br>Kimlik fotokopisi<br>İkametgah belgesi<br>ucak ve otel rezervasyonları varsa tur programı<br>Vukuatlı nüfüs kayıt örnegi nufus müdürlüğünden alınmış aslı ve yeni tarihli anne baba eş cocukları gösteren<br>Son 3 aylık banka hesap dökümü bankadan kaseli imzalı veya hesap cüzdanı güncel tarihli hesap bakiyesi bulunan randevu gününden son 1 hafta içinde alinmış olması gerekmektedir<br>Tapu fotokopileri varsa arac ruhsat fotokopileri";

?>
